### ISSUE TITLE
pkl model is ok ?

### ISSUE THREAD

**Issue by zhangyunming** [junedgar/openpifpaf_inference#1]
hi, i trained a model with basenet shufflenetv2*1,the type of the weight is .pkl.epoch150 ,so your inference can work for the pkl ? or how to translate the type to .pth with the .pkl  trained in project openpifpaf.

newer to pytorch,thanks.

**Comment by junedgar** [comment]
@zhangyunming
Sorry for late reply.
There is nothing difference between pkl or pth,  it just diffent in suffix.
But if you want use weight in the this project, you must export the pure model using the [file](https://github.com/vita-epfl/openpifpaf/blob/master/tests/test_onnx_export.py) in original project.
